# routes.yaml
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET, POST]

app_logout:
    path: /logout

admin_login:
    path: /admin/login
    controller: App\Controller\Admin\SecurityController::login
    methods: [GET, POST]

admin_logout:
    path: /admin/logout
